xsmall-diff:
  - size-below: 10
small-diff:
  - size-above: 9
  - size-below: 100
medium-diff:
  - size-above: 99
  - size-below: 500
large-diff:
  - size-above: 499
  - size-below: 1000
xlarge-diff:
  - size-above: 999
