name: "Add Labels"
on:
  pull_request:
    branches: [ main ]

jobs:
  label_module_type:
    runs-on: ubuntu-latest
    steps:
      - uses: srvaroa/labeler@master
        with:
          config_path: .github/labeler_config.yml
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  label_size_type:
    runs-on: ubuntu-latest
    steps:
      - uses: srvaroa/labeler@master
        with:
          config_path: .github/labeler_config_size.yml
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
