name: "Add Labels"
on:
  pull_request:
    branches: [ main ]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: srvaroa/labeler@v0.8
        with:
          config_path: .github/labeler_config.yml
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
