<<<<<<< HEAD
name: "Add Labels"
=======
name: "Pull Request Labeler"
>>>>>>> d8494ff (test actions)
on:
  pull_request:
    branches: [ main ]

jobs:
<<<<<<< HEAD
  label_module_type:
    runs-on: ubuntu-latest
    steps:
      - uses: srvaroa/labeler@v0.8
        with:
          config_path: .github/labeler_config.yml
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  label_size_type:
    runs-on: ubuntu-latest
    steps:
      - uses: srvaroa/labeler@v0.8
        with:
          config_path: .github/labeler_config_size.yml
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
=======
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        config_path: .github/labeler.yml
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
>>>>>>> d8494ff (test actions)
